# Generated by Django 3.2.5 on 2021-07-28 05:39

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('lap_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('lap_type', models.CharField(max_length=20)),
                ('lap_model', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='laptop', serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('phone_type', models.CharField(max_length=20)),
                ('phone_model', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone', serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('part_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('part_name', models.CharField(max_length=20)),
                ('part_type', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
