# Generated by Django 3.2.5 on 2021-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='contact',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='contact',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
