# Generated by Django 3.2.5 on 2021-07-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20210728_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='lap_model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_model',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
